# Generated by Django 5.2.4 on 2025-07-21 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_easy",
            "0002_business_approval_status_business_approved_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("semi_monthly", "Semi-Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "paye_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.25,
                        help_text="PAYE tax rate (e.g., 0.25 for 25%)",
                        max_digits=5,
                    ),
                ),
                (
                    "nis_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.03,
                        help_text="NIS contribution rate",
                        max_digits=5,
                    ),
                ),
                (
                    "nht_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.02,
                        help_text="NHT contribution rate",
                        max_digits=5,
                    ),
                ),
                (
                    "heart_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.003,
                        help_text="HEART contribution rate",
                        max_digits=5,
                    ),
                ),
                (
                    "ed_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0025,
                        help_text="Education tax rate",
                        max_digits=5,
                    ),
                ),
                (
                    "paye_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500000,
                        help_text="Annual PAYE threshold",
                        max_digits=10,
                    ),
                ),
                (
                    "nis_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000000,
                        help_text="Annual NIS ceiling",
                        max_digits=10,
                    ),
                ),
                (
                    "company_nis_number",
                    models.CharField(
                        blank=True,
                        help_text="Company NIS registration number",
                        max_length=50,
                    ),
                ),
                (
                    "company_paye_number",
                    models.CharField(
                        blank=True,
                        help_text="Company PAYE registration number",
                        max_length=50,
                    ),
                ),
                (
                    "overtime_rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Overtime rate multiplier",
                        max_digits=3,
                    ),
                ),
                (
                    "standard_hours_per_week",
                    models.IntegerField(
                        default=40, help_text="Standard working hours per week"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_config",
                        to="accounts_easy.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("payroll_summary", "Payroll Summary"),
                            ("tax_report", "Tax Report"),
                            ("ytd_summary", "YTD Summary"),
                            ("employee_summary", "Employee Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_period_start", models.DateField()),
                ("report_period_end", models.DateField()),
                (
                    "report_data",
                    models.JSONField(
                        default=dict, help_text="Report data in JSON format"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_reports",
                        to="accounts_easy.business",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeYTD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "ytd_gross_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_basic_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_overtime_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_bonus",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_paye_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_nis_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_nht_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_heart_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_ed_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_other_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "ytd_net_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ytd_records",
                        to="accounts_easy.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "employee__last_name"],
                "unique_together": {("employee", "year")},
            },
        ),
    ]
