# Generated by Django 5.2.4 on 2025-07-21 15:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_easy", "0003_payrollconfiguration_payrollreport_employeeytd"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance Bonus"),
                            ("holiday", "Holiday Bonus"),
                            ("attendance", "Attendance Bonus"),
                            ("sales", "Sales Bonus"),
                            ("special", "Special Recognition"),
                            ("other", "Other"),
                        ],
                        default="performance",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True, help_text="Is this bonus subject to tax?"
                    ),
                ),
                (
                    "is_applied",
                    models.BooleanField(
                        default=False,
                        help_text="Has this bonus been applied to a payroll run?",
                    ),
                ),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="accounts_easy.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "employee__last_name"],
                "unique_together": {("employee", "bonus_type", "month", "year")},
            },
        ),
    ]
