# Generated by Django 5.2.4 on 2025-08-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_easy", "0005_alter_business_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
